add code
shusuke0913/task1-4 pull request #1
Opened 2020-10-06 06:51 UTC by shusuke0913

課題1-4のコードを追加しました。
コードレビューお願い致します。

2020-10-08 10:55 UTC, manaberuit reviewed
いくつかコメントしましたので、ご確認ください^^

2020-10-08 10:55 UTC, manaberuit commented on index.html
> +    const janru = "[ジャンル]"
細かいですが、変数名にローマ字は使わない方が良いです。
（エンジニア業界の暗黙の了解になっていますね。。）

genreという英語を使いましょう！

2020-10-08 10:55 UTC, manaberuit commented on index.html
> +    const todo = ['[内容]机を片付ける、[ジャンル]掃除', '[内容]牛乳を買う、[ジャンル]買い物', '[内容]散歩する、[ジャンル]運動'];
こちらtodoは配列ですので、todosと複数形にしましょう！

2020-10-08 10:55 UTC, manaberuit commented on index.html
> +    const todo = ['[内容]机を片付ける、[ジャンル]掃除', '[内容]牛乳を買う、[ジャンル]買い物', '[内容]散歩する、[ジャンル]運動'];
こちらのtodos配列の各要素はせっかくなのでオブジェクトを使用しましょう！
```
{
  content: '机を片付ける'
  genre: '掃除'
}
```
のようなオブジェクを各要素に格納するイメージです。

2020-10-08 10:55 UTC, manaberuit commented on index.html
> +    console.log(`${i}: ${todo[i]}`);
上記の修正によって、こちらの記述も変更する必要がありますね^^

2020-12-16 13:00 UTC, myzktkyk requested changes
1点確認をさせていただいてます！

2020-12-16 13:00 UTC, myzktkyk commented on index.html
> +    for (let i = 1; i < 2; i++) {
`for` 文が増殖していますが、これはどういう意図でしょうか？
以下の様にすればよいと思ったのですが、それではダメな理由があるのでしょうか？

```
    for (let i = 0; i < todo.length; i++) {
        console.log(`${i}: ${content}${todos[i].content}` + "、",`${genre}${todos[i].genre}`);
    }
```

2020-12-17 01:27 UTC, shusuke0913 commented on index.html
> +    for (let i = 1; i < 2; i++) {
コードレビューありがとうございます。
ダメな理由などはなく、増殖したのはコードを簡単にする方法が思いつかなかったからです。

2020-12-21 09:47 UTC, merged